import uuid
import time
from datetime import datetime
import config.settings as settings
from models import ExceptionModel, ExceptionStatus
from agents.context_builder import ContextBuilderAgent
from agents.root_cause import RootCauseAgent
from agents.classifier import ClassifierAgent
from agents.action_recommender import ActionRecommenderAgent
from agents.prompt_engineer import PromptEngineerAgent
from agents.tracer import AgentTracer
from mcp_client import MCPClient
import logging

logger = logging.getLogger(__name__)

class ExceptionOrchestrator:
    def __init__(self, store):
        self.store = store
        self.context_builder = ContextBuilderAgent()
        self.prompt_engineer = PromptEngineerAgent()
        self.root_cause_agent = RootCauseAgent()
        self.classifier = ClassifierAgent()
        self.recommender = ActionRecommenderAgent()
        self.deep_agent = None
        self.last_trace = None
        self.mcp_client = MCPClient()
        if settings.AZURE_OPENAI_ENABLED:
            self._init_deep_agent()

    def _init_deep_agent(self):
        try:
            from deepagents import create_deep_agent
            from langchain_openai import AzureChatOpenAI
            model = AzureChatOpenAI(azure_endpoint=settings.AZURE_OPENAI_ENDPOINT,
                azure_deployment=settings.AZURE_OPENAI_DEPLOYMENT,
                api_key=settings.AZURE_OPENAI_API_KEY, api_version=settings.AZURE_OPENAI_API_VERSION, temperature=0)
            self.deep_agent = create_deep_agent(model=model, tools=[], system_prompt="P2P Exception AI")
            logger.info("[OK] Deep Agent initialized")
        except Exception as e:
            logger.warning(f"[INFO] Deep Agent failed: {e}. Using rule-based mode.")

    def process(self, raw_input):
        tracer = AgentTracer()

        # Step 1: Context Builder
        t = time.time()
        context = self.context_builder.build(raw_input)
        ms = int((time.time() - t) * 1000)
        tracer.record(
            "Context Builder",
            f"Raw case {raw_input.get('case_id', '?')}",
            f"type={context.exception_type}, exposure=${context.financial_exposure:,.0f}, deviation={context.deviation_point}",
            details={
                "case_id": context.case_id,
                "exception_type": context.exception_type,
                "financial_exposure": context.financial_exposure,
                "severity_score": context.severity_score,
                "deviation_point": context.deviation_point,
                "actual_path": context.actual_path,
                "happy_path": context.happy_path,
                "vendor": context.vendor,
            },
            duration_ms=ms,
        )

        # Stage 0: Prompt Engineer — fetch historical first so vendor patterns
        # can be included in the prompts for both GPT-4o and rule-based paths.
        t = time.time()
        historical = self.store.get_historical_cases(context.exception_type)
        prompt_package = self.prompt_engineer.generate(context, historical_cases=historical)
        ms = int((time.time() - t) * 1000)
        tracer.record(
            "Prompt Engineer",
            f"Context: {context.exception_type}",
            f"Generated by: {prompt_package.generated_by}. Risk flags: {len(prompt_package.risk_flags)}",
            details={
                "generated_by": prompt_package.generated_by,
                "context_summary": prompt_package.context_summary,
                "risk_flags": prompt_package.risk_flags,
            },
            duration_ms=ms,
        )
        tracer.record_connection(
            "Context Builder", "Root Cause Agent",
            f"Passing context: type={context.exception_type}, path={' -> '.join(context.actual_path)}",
            {"exception_type": context.exception_type},
        )

        # Step 2: Root Cause — reuse historical already fetched above
        t = time.time()
        root_cause = self.root_cause_agent.analyze(context, historical, prompt_package)
        ms = int((time.time() - t) * 1000)
        tracer.record(
            "Root Cause Agent",
            f"Context: {context.exception_type}, Historical: {len(historical)} matches",
            f"Hypothesis: {root_cause.hypothesis[:80]}... Confidence: {root_cause.confidence:.0%}",
            details={
                "historical_matches": len(historical),
                "hypothesis": root_cause.hypothesis,
                "confidence": root_cause.confidence,
                "supporting_cases": root_cause.supporting_cases,
                "causal_factors": root_cause.causal_factors,
            },
            duration_ms=ms,
        )
        tracer.record_connection(
            "Root Cause Agent", "Classifier Agent",
            f"Root cause confidence {root_cause.confidence:.0%}. Passing to classifier.",
            {"confidence": root_cause.confidence},
        )

        # Step 3: Classifier
        t = time.time()
        classification = self.classifier.classify(context, root_cause, prompt_package, historical_cases=historical)
        ms = int((time.time() - t) * 1000)
        tracer.record(
            "Classifier Agent",
            f"Context + Root cause (confidence={root_cause.confidence:.0%})",
            f"Category: {classification.category}, Priority: P{classification.priority}, Novel: {classification.is_novel}, Routing: {classification.routing.upper()}",
            details={
                "category": classification.category,
                "priority": classification.priority,
                "is_novel": classification.is_novel,
                "routing": classification.routing,
                "confidence": classification.confidence,
            },
            duration_ms=ms,
        )
        tracer.record_connection(
            "Classifier Agent", "Action Recommender",
            f"Classified as '{classification.category}' P{classification.priority}. Route: {classification.routing.upper()}.",
            {"category": classification.category, "routing": classification.routing},
        )

        # Step 4: Recommender
        t = time.time()
        policies = self.store.get_policies(classification.category)
        action_type, action_params, reasoning, erp_recommendation = self.recommender.recommend(
            context, classification, policies, prompt_package
        )
        ms = int((time.time() - t) * 1000)
        tracer.record(
            "Action Recommender",
            f"Category: {classification.category}, Policies: {len(policies)}",
            f"Recommended: {action_type}. {reasoning[:80]}",
            details={
                "action_type": action_type,
                "reasoning": reasoning,
                "policies_checked": len(policies),
                "erp_transaction": erp_recommendation.get("transaction"),
            },
            duration_ms=ms,
        )

        # Step 5: Decision Router
        status = ExceptionStatus.PENDING_DECISION if classification.routing == "human" else ExceptionStatus.APPROVED
        tracer.record_connection(
            "Action Recommender", "Decision Router",
            f"Final: {action_type}. Route: {classification.routing.upper()}. {'Human review needed.' if status == ExceptionStatus.PENDING_DECISION else 'Auto-approved.'}",
            {"action_type": action_type, "routing": classification.routing},
        )
        tracer.record(
            "Decision Router",
            f"Action: {action_type}, Route: {classification.routing}",
            f"Status: {status.value}. {'Human review required.' if status == ExceptionStatus.PENDING_DECISION else 'Auto-executed.'}",
            details={"final_status": status.value, "action": action_type, "routing": classification.routing},
            duration_ms=0,
        )

        # Save trace
        trace_summary = tracer.get_summary()
        self.last_trace = trace_summary

        exc = ExceptionModel(
            id=str(uuid.uuid4()),
            status=status,
            context=context,
            root_cause=root_cause,
            classification=classification,
            recommended_action=action_type,
            recommended_action_params={**action_params, "agent_trace": trace_summary},
            ai_reasoning=reasoning,
            prompt_package=prompt_package.to_dict(),
            erp_recommendation=erp_recommendation,
            erp_execution_status="pending" if erp_recommendation else None,
        )
        self.store.save_exception(exc)

        if classification.routing == "human":
            logger.info(f"[INFO] Sending Teams notification for {exc.id}")
            try:
                self.mcp_client.notify_teams(
                    case_id=exc.context.case_id,
                    issue=exc.context.exception_type,
                    priority=exc.classification.priority,
                    recommendation=exc.recommended_action,
                    financial_exposure=exc.context.financial_exposure,
                    exception_uuid=exc.id,
                    erp_recommendation=exc.erp_recommendation,
                    assigned_team=exc.context.assigned_team,
                    responsible_team=getattr(exc.classification, "responsible_team", ""),
                )
            except Exception as e:
                logger.error(f"[ERROR] Failed to send Teams notification: {e}")

        return exc

    def get_last_trace(self):
        """Return trace from most recent process() call."""
        return self.last_trace or {}